###############################
#    BedwarsXP  经验起床插件  #
#       By.SakuraKooi         #
###############################

#设置资源可兑换为的XP数
XP:
    # 铜可兑换为的XP
    bronze: 1
    # 铁可兑换为的XP
    iron: 5
    # 金可兑换为的XP
    gold: 10
    # 如有其他自行添加的资源也可以在此处按格式添加
    #custom: 233
#  请务必保证起床插件中配置的资源在此处都有对应经验值

#获得XP的提示
#  使用%xp%代替获得的XP
#  插件会尝试使用ActionBar来发送,如发送失败(版本不匹配等原因)会使用聊天发送
#  更改为空('')来禁用发送信息
Message: '&a你获得了 &6&l%xp% &a点经验'

#是否在商店新增将经验重新兑换回铜铁金的菜单
Add_Res_Shop: true

#玩家死亡扣除经验
#  扣除的经验 = 玩家拥有经验 x (DeathCostXP)%
#  请填写0-100 (百分比)
#  设置为0关闭此功能
#  固定扣除功能已被移除
DeathCostXP: 0

#玩家死亡掉落经验
#  开启此项后玩家死亡扣除的经验将掉在地上, 可以被其他玩家捡起
#  掉落的经验 = 玩家拥有经验 x (DeathCostXP)% x (DeathDropXP)%
#  请填写0-100 (百分比)
#  设置为0关闭此功能
DeathDropXP: 100

#死亡直接把经验添加给击杀者而不是掉落经验瓶
DontDropExpBottle: false

#玩家可携带的最大经验
#  超过该经验将无法捡取
#  设置为0关闭此功能
MaxXP: 0
MaxXPMessage: '&4你携带的经验已达上限'

#完全经验起床模式
#  设置为false : 玩家捡取资源获得经验,在商店将经验重新兑换回铜铁金购买东西
#  设置为true  : 玩家捡取资源获得经验,并可以在商店直接使用经验购买东西
Full_XP_Bedwars: true

#配置文件版本
#  请务必不要动这个
#  乱动此项导致配置文件被重置概不负责→_→
ConfigVersion: 2

